#!/usr/bin/env bash
#
# Step 3: dracut Initramfs Configuration
#
# This script:
# - Installs dracut and required modules
# - Configures dracut for TPM2, LUKS, and Secure Boot
# - Sets up Unified Kernel Image (UKI) generation
# - Generates initial UKI
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/utils.sh
source "${SCRIPT_DIR}/utils.sh"

# State file from previous step
readonly STATE_FILE="/tmp/arch-install-state"
readonly CONFIG_DIR="$(dirname "$SCRIPT_DIR")/configs"

# Load state from previous step
load_state() {
    if [[ ! -f "$STATE_FILE" ]]; then
        print_error "State file not found. Did you run previous steps first?"
        exit 1
    fi

    # shellcheck source=/dev/null
    source "$STATE_FILE"
}

# Install dracut and dependencies
install_dracut() {
    print_info "Installing dracut and dependencies..."

    local packages=(
        dracut
        dracut-hooks
        tpm2-tss
        elfutils
        binutils
    )

    chroot_cmd "pacman -S --noconfirm --needed ${packages[*]}"

    print_success "dracut installed"
}

# Create dracut configuration directory
setup_dracut_dirs() {
    print_info "Setting up dracut configuration directories..."

    local dracut_conf_dir="${MOUNT_POINT}/etc/dracut.conf.d"
    ensure_dir "$dracut_conf_dir"

    print_success "Directories created"
}

# Get kernel command line parameters
get_kernel_cmdline() {
    local root_device="/dev/mapper/${LUKS_NAME}"
    local root_uuid
    # Run blkid on host since the device mapper only exists there
    root_uuid=$(blkid -s UUID -o value "${root_device}")

    # Build command line
    local cmdline=""
    cmdline+="root=UUID=${root_uuid} "
    cmdline+="rootfstype=ext4 "
    cmdline+="rd.luks.name=${LUKS_UUID}=${LUKS_NAME} "
    cmdline+="rd.luks.options=${LUKS_UUID}=tpm2-device=auto "
    cmdline+="rw quiet splash"

    echo "$cmdline"
}

# Configure dracut kernel command line
configure_dracut_cmdline() {
    print_info "Configuring kernel command line..."

    local cmdline
    cmdline=$(get_kernel_cmdline)

    local cmdline_conf="${MOUNT_POINT}/etc/dracut.conf.d/cmdline.conf"

    cat > "$cmdline_conf" <<EOF
# Kernel command line configuration
# This is embedded into the Unified Kernel Image (UKI)

kernel_cmdline="${cmdline}"
EOF

    print_info "Kernel cmdline: $cmdline"
    print_success "Command line configured"
}

# Configure dracut flags
configure_dracut_flags() {
    print_info "Configuring dracut build flags..."

    local flags_conf="${MOUNT_POINT}/etc/dracut.conf.d/flags.conf"

    cat > "$flags_conf" <<EOF
# dracut build flags

# Use host-only mode for smaller images
hostonly="yes"
hostonly_cmdline="no"

# Compression
compress="zstd"

# Show verbose output during build
dracut_verbose="yes"

# Add TPM2 modules
add_dracutmodules+=" tpm2-tss "

# Filesystem support
filesystems+=" ext4 vfat "
EOF

    print_success "Build flags configured"
}

# Configure dracut for TPM2
configure_dracut_tpm() {
    print_info "Configuring dracut TPM2 support..."

    local tpm_conf="${MOUNT_POINT}/etc/dracut.conf.d/tpm2-tss.conf"

    cat > "$tpm_conf" <<EOF
# TPM2 support configuration

# Force inclusion of TPM2 tools and libraries
install_items+=" /usr/lib/libtss2-*.so* "
install_items+=" /usr/bin/tpm2_* "

# Include cryptsetup with TPM2 support
install_items+=" /usr/lib/cryptsetup/libcryptsetup-token-systemd-tpm2.so "

# Add kernel modules for TPM
add_drivers+=" tpm tpm_tis tpm_crb "
EOF

    print_success "TPM2 configured"
}

# Configure dracut for Secure Boot
configure_dracut_secureboot() {
    print_info "Configuring dracut Secure Boot support..."

    local sb_conf="${MOUNT_POINT}/etc/dracut.conf.d/secureboot.conf"

    cat > "$sb_conf" <<EOF
# Secure Boot configuration
# Keys will be generated by sbctl in the next step

# Enable UKI generation
uefi="yes"
uefi_stub="/usr/lib/systemd/boot/efi/linuxx64.efi.stub"

# UKI output location
uefi_outdir="/boot/EFI/Linux"

# Secure Boot keys (will be set up by sbctl)
# These paths will be used after sbctl generates keys
uefi_secureboot_cert="/usr/share/secureboot/keys/db/db.pem"
uefi_secureboot_key="/usr/share/secureboot/keys/db/db.key"

# Don't sign yet - sbctl will handle signing
# uefi_secureboot_sign="yes"
EOF

    print_success "Secure Boot support configured"
}

# Configure dracut modules
configure_dracut_modules() {
    print_info "Configuring dracut modules..."

    local modules_conf="${MOUNT_POINT}/etc/dracut.conf.d/modules.conf"

    cat > "$modules_conf" <<EOF
# dracut modules configuration

# Add required modules
add_dracutmodules+=" systemd systemd-initrd systemd-cryptsetup crypt dm kernel-modules "

# Omit unnecessary modules for smaller image
omit_dracutmodules+=" network nfs nbd iscsi "
EOF

    print_success "Modules configured"
}

# Create UKI output directory
create_uki_dir() {
    print_info "Creating UKI output directory..."

    local uki_dir="${MOUNT_POINT}/boot/EFI/Linux"
    ensure_dir "$uki_dir"

    print_success "UKI directory created: $uki_dir"
}

# Setup dracut pacman hook
setup_dracut_hook() {
    print_info "Setting up dracut pacman hook..."

    # The dracut-hooks package should install this automatically
    # Verify it exists
    local hook_file="${MOUNT_POINT}/usr/share/libalpm/hooks/90-dracut-install.hook"

    if [[ -f "$hook_file" ]]; then
        print_success "dracut pacman hook is installed"
    else
        print_warn "dracut hook not found, kernels may not auto-rebuild"
        print_info "Creating custom dracut hook..."

        local hook_dir="${MOUNT_POINT}/etc/pacman.d/hooks"
        ensure_dir "$hook_dir"

        cat > "${hook_dir}/90-dracut-install.hook" <<EOF
[Trigger]
Type = Path
Operation = Install
Operation = Upgrade
Target = usr/lib/modules/*/vmlinuz

[Action]
Description = Updating initramfs with dracut...
When = PostTransaction
Exec = /usr/bin/dracut --force --hostonly --no-hostonly-cmdline
EOF

        print_success "Custom dracut hook created"
    fi
}

# Generate initial dracut image
generate_dracut_image() {
    print_info "Generating initial dracut initramfs..."
    echo
    print_warn "This may take a few minutes..."
    echo

    # Find installed kernel version
    local kernel_version
    kernel_version=$(chroot_cmd "ls /usr/lib/modules" | grep -v extramodules | head -n1)

    if [[ -z "$kernel_version" ]]; then
        print_error "No kernel found in /usr/lib/modules"
        return 1
    fi

    print_info "Kernel version: $kernel_version"

    # Generate UKI (unsigned for now, will be signed in next step)
    if chroot_cmd "dracut --force --hostonly --no-hostonly-cmdline --uefi --kver ${kernel_version}"; then
        print_success "dracut image generated"
    else
        print_error "dracut generation failed"
        return 1
    fi

    # Check if UKI was created
    local uki_path="${MOUNT_POINT}/boot/EFI/Linux/arch-linux.efi"
    if [[ -f "$uki_path" ]]; then
        print_success "UKI created: /boot/EFI/Linux/arch-linux.efi"
        ls -lh "$uki_path"
    else
        print_warn "UKI not found at expected location"
        print_info "Checking /boot/EFI/Linux contents:"
        ls -la "${MOUNT_POINT}/boot/EFI/Linux/" || true
    fi
}

# Update dracut configuration to disable signing temporarily
update_secureboot_config() {
    print_info "Updating Secure Boot configuration..."

    local sb_conf="${MOUNT_POINT}/etc/dracut.conf.d/secureboot.conf"

    # Comment out signing options since sbctl will handle it
    sed -i 's/^uefi_secureboot_/#uefi_secureboot_/' "$sb_conf"

    print_success "Configuration updated for sbctl signing"
}

# Display configuration summary
show_configuration() {
    echo
    print_separator "="
    print_success "dracut configuration complete!"
    print_separator "="
    echo

    print_info "Configuration files created:"
    echo "  /etc/dracut.conf.d/cmdline.conf     - Kernel command line"
    echo "  /etc/dracut.conf.d/flags.conf       - Build flags"
    echo "  /etc/dracut.conf.d/tpm2-tss.conf    - TPM2 support"
    echo "  /etc/dracut.conf.d/secureboot.conf  - Secure Boot/UKI"
    echo "  /etc/dracut.conf.d/modules.conf     - Module selection"
    echo

    print_info "Kernel command line:"
    get_kernel_cmdline
    echo

    print_info "UKI location:"
    echo "  /boot/EFI/Linux/arch-linux.efi"
    echo
}

# Main function
main() {
    print_info "=== dracut Initramfs Configuration ==="
    echo

    # Require root
    require_root || exit 1

    # Load state from previous step
    load_state

    # Verify mount point
    if [[ ! -d "$MOUNT_POINT" ]]; then
        print_error "Mount point not found: $MOUNT_POINT"
        exit 1
    fi

    # Install dracut
    install_dracut

    # Setup directories
    setup_dracut_dirs

    # Create UKI directory
    create_uki_dir

    # Configure dracut
    configure_dracut_cmdline
    configure_dracut_flags
    configure_dracut_tpm
    configure_dracut_secureboot
    configure_dracut_modules

    # Setup pacman hook
    setup_dracut_hook

    # Generate initial image
    generate_dracut_image

    # Update config for sbctl
    update_secureboot_config

    # Show summary
    show_configuration

    print_success "Step 3 complete: dracut configured and initramfs generated"
    echo
    print_info "Next step: Run 04-secure-boot.sh to setup Secure Boot signing"
}

# Run main function
main "$@"
